### ISSUE TITLE
Permission Denied error

### ISSUE THREAD

**Issue by nbently** [TerrapinWorks/dymo#1]
The file J13938.html has been uploaded as label.html

Errors from saving file: Array ( ) 

Errors from printing label: Array ( [0] => Traceback (most recent call last): [1] => File "/home/pi/dymo/jobName.py", line 30, in [2] => f = open(out, 'w+') [3] => IOError: [Errno 13] Permission denied: '/home/pi/dymo/clipboard.txt' )

**Comment by blepfo** [comment]
When the code from the pi was edited and pulled from the git repo, it seems the permissions got messed up. It's fixed now, but I'll be sure to keep an eye out whenever we update jobName.py in the future.
